spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.TYPE: trace